
# 基础配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: [dev, servicedev, commondev]     # 使用dev配置文件
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:      # 文件相关
      max-file-size: 20MB
      max-request-size: 20MB
  resources:
    static-locations:




mybatis-plus:
  type-aliases-package: com.xhy.wblog.pojo
  configuration:
    use-generated-keys: true
  global-config:
    db-config:
      id-type: auto


