
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test_mybatis?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    druid:
      max-wait: 5000
      max-active: 50
      min-idle: 5
      initial-size: 10
server:
  port: 8888

logging:
  level:
    com.zcwxdqy.agedapp: debug

aged:


  # 跨域
  cfg:
    cors-origins:
      - http://localhost:63342
      - http://localhost:63341
      - http://172.20.10.4:8080
      - http://172.20.10.4:8081

  # 图片上传位置
  upload:
    base-path: F:/wblog/
    upload-path: upload/
    image-path: img/
    video-path: video/